### ISSUE TITLE
[feature] Support `ast-grep-ignore` in Python API

### ISSUE THREAD

**Issue by etiennebacher** [ast-grep/ast-grep#1278]
# ⭐ Suggestion

It would be great if the Python API could support the keywords to ignore lines. For example this shouldn't return a node:

```python
from ast_grep_py import SgRoot

root = SgRoot(
    """
# ast-grep-ignore
print('hello world')              
""",
    "python",
).root()

root.find(pattern="print($A)").text()

# "print('hello world')"
```
On the playground, it doesn't match the text: https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoicHl0aG9uIiwicXVlcnkiOiJwcmludCgkQSkiLCJyZXdyaXRlIjoicHJpbnQoXCJmb29cIikiLCJjb25maWciOiIjIFlBTUwgUnVsZSBpcyBtb3JlIHBvd2VyZnVsIVxuIyBodHRwczovL2FzdC1ncmVwLmdpdGh1Yi5pby9ndWlkZS9ydWxlLWNvbmZpZy5odG1sI3J1bGVcbnJ1bGU6XG4gIGFueTpcbiAgICAtIHBhdHRlcm46IGNvbnNvbGUubG9nKCRBKVxuICAgIC0gcGF0dGVybjogY29uc29sZS5kZWJ1ZygkQSlcbmZpeDpcbiAgbG9nZ2VyLmxvZygkQSkiLCJzb3VyY2UiOiIjIGFzdC1ncmVwLWlnbm9yZVxucHJpbnQoJ2hlbGxvIHdvcmxkJykifQ==

# 💻 Use Cases

Better feature parity with the CLI.

**Comment by HerringtonDarkholme** [comment]
I don't think this should be supported in Python API since `ignore` is for ast-grep rule and Python API does not have the concept of rule. 

On the other hand, you can implement ignore logic using Python API `prev` / `range` / `parent`. Reference: https://github.com/ast-grep/ast-grep/blob/5c7485bb731cfba264b3b4c6e8eb4952b69aca28/crates/config/src/combined.rs#L166-L189

**Comment by etiennebacher** [comment]
I see, thanks for the quick answer
