### ISSUE TITLE
[bug] TypeScript decorators cannot be collected in a multi meta variable

### ISSUE THREAD

**Issue by ttacon** [ast-grep/ast-grep#1503]
# ⏯ Playground Link

[Playground link with relevant code](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoidHlwZXNjcmlwdCIsInF1ZXJ5IjoiQCRERUNPMVxuQCRERUNPMlxuQCRERUNPM1xuZXhwb3J0IGNsYXNzICRDTEFTU05BTUUgZXh0ZW5kcyBDb250cm9sbGVyIHsgJCQkQk9EWSB9IiwicmV3cml0ZSI6IkAkREVDTzFcbkAkREVDTzJcbkAkREVDTzNcbmV4cG9ydCBjbGFzcyAkQ0xBU1NOQU1FIGV4dGVuZHMgQ29udHJvbGxlciB7XG4gICAgJCQkQk9EWVxuXG4gICAgQEdldCgne2lkfScpXG4gICAgcHVibGljIGFzeW5jIGdldE5ld0V4YW1wbGUoQFBhdGgoJ2lkJykgaWQ6IHN0cmluZyk6IFByb21pc2U8bnVtYmVyPiB7XG4gICAgICAgIFxuICAgIH1cbn0iLCJzdHJpY3RuZXNzIjoic21hcnQiLCJzZWxlY3RvciI6IiIsImNvbmZpZyI6IiMgWUFNTCBSdWxlIGlzIG1vcmUgcG93ZXJmdWwhXG4jIGh0dHBzOi8vYXN0LWdyZXAuZ2l0aHViLmlvL2d1aWRlL3J1bGUtY29uZmlnLmh0bWwjcnVsZVxucnVsZTpcbiAgYW55OlxuICAgIC0gcGF0dGVybjogY29uc29sZS5sb2coJEEpXG4gICAgLSBwYXR0ZXJuOiBjb25zb2xlLmRlYnVnKCRBKVxuZml4OlxuICBsb2dnZXIubG9nKCRBKSIsInNvdXJjZSI6ImltcG9ydCB7IEJvZHksIENvbnRyb2xsZXIsIEdldCwgTWlkZGxld2FyZXMsIFBhdGgsIFBvc3QsIFJvdXRlLCBTdWNjZXNzUmVzcG9uc2UgfSBmcm9tICd0c29hJztcblxuaW1wb3J0IHsgVGFncyB9IGZyb20gJ0B0c29hL3J1bnRpbWUnO1xuaW1wb3J0IHsgRXhhbXBsZVJlc291cmNlIH0gZnJvbSAnfi9tb2RlbHMvRXhhbXBsZVJlc291cmNlJztcbmltcG9ydCB7IGFwaUtleUF1dGhNaWRkbGV3YXJlIH0gZnJvbSAnfi9taWRkbGV3YXJlL3NlY3VyaXR5JztcblxuQFJvdXRlKCdleGFtcGxlLXJlc291cmNlJylcbkBUYWdzKCdFeGFtcGxlIHRhZ2dpbmcnKVxuQE1pZGRsZXdhcmVzKGFwaUtleUF1dGhNaWRkbGV3YXJlKVxuZXhwb3J0IGNsYXNzIEV4YW1wbGVSZXNvdXJjZUNvbnRyb2xsZXIgZXh0ZW5kcyBDb250cm9sbGVyIHtcbiAgQFN1Y2Nlc3NSZXNwb25zZSgyMDEsICdDcmVhdGVkJylcbiAgQFBvc3QoKVxuICBwdWJsaWMgYXN5bmMgY3JlYXRlRXhhbXBsZShcbiAgICBAQm9keSgpIHJlcTogT21pdDxFeGFtcGxlUmVzb3VyY2UsICdpZCcgfCAnY3JlYXRlZEF0Jz4sXG4gICk6IFByb21pc2U8RXhhbXBsZVJlc291cmNlPiB7XG4gICAgdGhpcy5zZXRTdGF0dXMoMjAxKTtcbiAgICByZXR1cm4gcmVzcG9uc2U7XG4gIH1cbn1cbiJ9)

# 💻 Code

Code:

```
import { Body, Controller, Get, Middlewares, Path, Post, Route, SuccessResponse } from 'tsoa';

import { Tags } from '@tsoa/runtime';
import { ExampleResource } from '~/models/ExampleResource';
import { apiKeyAuthMiddleware } from '~/middleware/security';

@Route('example-resource')
@Tags('Example tagging')
@Middlewares(apiKeyAuthMiddleware)
export class ExampleResourceController extends Controller {
  @SuccessResponse(201, 'Created')
  @Post()
  public async createExample(
    @Body() req: Omit<ExampleResource, 'id' | 'createdAt'>,
  ): Promise<ExampleResource> {
    this.setStatus(201);
    return response;
  }
}
```

Pattern:

I hadn't turned this into a YAML rule file, so the matching pattern that I expected to work was:
```
@$$$DECORATORS
export class $CLASSNAME extends Controller { $$$BODY }
```

That I then wanted to rewrite with:

```
@$$$DECORATORS
export class $CLASSNAME extends Controller {
    $$$BODY

    @Get('{id}')
    public async getNewExample(@Path('id') id: string): {
        this.setStatus(501);
    }
}
```

# 🙁 Actual behavior

This didn't match, due to decorators being parsed with no parent AST node grouping them together (see screenshot).

<img width="460" alt="Screenshot 2024-10-01 at 9 39 07 PM" src="https://github.com/user-attachments/assets/6cf42a89-eb30-48c5-8221-4025ad54f9b2">

To get this to match, I had to use:

```
@$DECORATOR1
@$DECORATOR2
@$DECORATOR3
export class $CLASSNAME extends Controller { $$$BODY }
```

# 🙂 Expected behavior

I had expected to be able to collect multiple decorator nodes into a single multi meta variable.

**Comment by HerringtonDarkholme** [comment]
It is not possible to construct a multi-metavariable to match decorator because `$$$VAR` will not be detected as decorator inside export statement.  Also see https://ast-grep.github.io/advanced/pattern-parse.html

You can instead use rewriter for multiple AST nodes modification. https://ast-grep.github.io/reference/yaml/rewriter.html https://ast-grep.github.io/advanced/find-n-patch.html

**Comment by HerringtonDarkholme** [comment]
The problem is 

```ts
@$$$DECO1
export class $CLASSNAME extends Controller { $$$BODY }
```
is parsed to a pattern like below

<img width="434" alt="image" src="https://github.com/user-attachments/assets/9b5e4ed5-0d7d-4979-b2f2-a56af63571f6">

You can see `@$$$DECO1` is parsed as one single AST under export.

You don't need to use one pattern for this rewrite, instead, using [yaml rule](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InR5cGVzY3JpcHQiLCJxdWVyeSI6IiIsInJld3JpdGUiOiIiLCJzdHJpY3RuZXNzIjoic21hcnQiLCJzZWxlY3RvciI6IiIsImNvbmZpZyI6InJ1bGU6XG4gIGtpbmQ6IGNsYXNzX2JvZHlcbiAgaW5zaWRlOlxuICAgIHBhdHRlcm46IGNsYXNzICRBIGV4dGVuZHMgQ29udHJvbGxlciB7ICQkJEJPRFkgfVxuZml4OiB8LVxuICB7XG4gICAgJCQkQk9EWVxuICAgIFxuICAgIEBHZXQoJ3tpZH0nKVxuICAgIHB1YmxpYyBhc3luYyBnZXROZXdFeGFtcGxlKEBQYXRoKCdpZCcpIGlkOiBzdHJpbmcpOiB7XG4gICAgICAgIHRoaXMuc2V0U3RhdHVzKDUwMSk7XG4gICAgfVxuICB9Iiwic291cmNlIjoiaW1wb3J0IHsgQm9keSwgQ29udHJvbGxlciwgR2V0LCBNaWRkbGV3YXJlcywgUGF0aCwgUG9zdCwgUm91dGUsIFN1Y2Nlc3NSZXNwb25zZSB9IGZyb20gJ3Rzb2EnO1xuXG5pbXBvcnQgeyBUYWdzIH0gZnJvbSAnQHRzb2EvcnVudGltZSc7XG5pbXBvcnQgeyBFeGFtcGxlUmVzb3VyY2UgfSBmcm9tICd+L21vZGVscy9FeGFtcGxlUmVzb3VyY2UnO1xuaW1wb3J0IHsgYXBpS2V5QXV0aE1pZGRsZXdhcmUgfSBmcm9tICd+L21pZGRsZXdhcmUvc2VjdXJpdHknO1xuXG5AUm91dGUoJ2V4YW1wbGUtcmVzb3VyY2UnKVxuQFRhZ3MoJ0V4YW1wbGUgdGFnZ2luZycpXG5ATWlkZGxld2FyZXMoYXBpS2V5QXV0aE1pZGRsZXdhcmUpXG5leHBvcnQgY2xhc3MgRXhhbXBsZVJlc291cmNlQ29udHJvbGxlciBleHRlbmRzIENvbnRyb2xsZXIge1xuICBAU3VjY2Vzc1Jlc3BvbnNlKDIwMSwgJ0NyZWF0ZWQnKVxuICBAUG9zdCgpXG4gIHB1YmxpYyBhc3luYyBjcmVhdGVFeGFtcGxlKFxuICAgIEBCb2R5KCkgcmVxOiBPbWl0PEV4YW1wbGVSZXNvdXJjZSwgJ2lkJyB8ICdjcmVhdGVkQXQnPixcbiAgKTogUHJvbWlzZTxFeGFtcGxlUmVzb3VyY2U+IHtcbiAgICB0aGlzLnNldFN0YXR1cygyMDEpO1xuICAgIHJldHVybiByZXNwb25zZTtcbiAgfVxufVxuIn0=
) is much easier.

<img width="1393" alt="image" src="https://github.com/user-attachments/assets/9d55a6d8-7963-4e67-85d8-0a29db1ebda1">
