### ISSUE TITLE
ast-grep still overwrites `sg` command by default

### ISSUE THREAD

**Issue by m1ntySkye** [ast-grep/ast-grep#1659]
# ⭐ Suggestion

after installing ast-grep using pipx, cargo or npm, the core linux command `sg` is overwritten. (I've tried all these package managers).
I can see that there's a warning about this in the installation page. I can also see that there have been numerous issues opened, the one you link to being #56.

your solution so far seems to have been adding the ast-grep alternative alias, although this seems pointless if `sg` is still changed to point to your binary. renaming core utilities is dangerous & should not be a default behavior.

having a shortened but still descriptive alias like [astg, suggested here](https://github.com/ast-grep/ast-grep/issues/56#issuecomment-1545591541) or even better [letting the user choose an alias](https://github.com/ast-grep/ast-grep/issues/778#issuecomment-1950231748)

while you could maybe make it safer by sniffing the OS during installation & choosing not to overwrite if it's in use, this is again just adding complexity that isn't needed.
In the end, it seems like a choice you've made early on to keep this alias but I hope enough people have complained to make it clear the sane thing to do is simply remove sg as an alias.

# 💻 Use Cases

As a time poor dev, who just wants to quickly experiment with a neat looking tool, things like this that introduce some risk with no instantly obvious solution increases the barrier to entry.

**Comment by HerringtonDarkholme** [comment]
Hi @m1ntySkye,

Thank you for trying out ast-grep and for submitting this issue.

As a kind suggestion, it may be helpful to tweak your path settings based on how you installed the command. You can move the npm/cargo/pip directory after the system path to avoid conflicts. Moving non-system 

The shadow-utils command is lesser known, at least to the author, and it seems this issue has not been reported since the documentation update.

We respect our users and understand that while the impact on Linux commands issue received minimal reports from linux community and existing complaints are idealogical, removing the command name could lead to undesirable user churn on other OS. If we receive enough feedback from Linux users, we will consider deprecating the command. You are more than welcome to recommend ast-grep to your Linux friends and coworkers, and drop more feedback to us. We lack Linux users and your input is invaluable.

As a hobby project, the ast-grep maintainer has limited time to dedicate to this tool. And the project does not have much resource.  Please help us by providing more information in the original issue. https://github.com/ast-grep/ast-grep/issues/56

---
What device are you installing ast-grep?: Personal device, Server, User's computer as a dependency
How are you using sg the shadow-utils?
How sg the ast-grep command impact you?: Break your workflow/server script? ast-grep is overridden by shadow-utils? Or because it is a bad practice?
__

Thank you for your understanding and support.

**Comment by HerringtonDarkholme** [comment]
Closing in favor of the original issue
