### ISSUE TITLE
[bug] `--globs` CLI flag (no longer) seem to work

### ISSUE THREAD

**Issue by evangalen** [ast-grep/ast-grep#1687]
### Please read the FAQ for the bug you encountered.

- [X] I have read the existing FAQ

### ⏯ Playground Link

NA

### 🙁 Actual behavior

I'm trying to use `--globs` CLI flag with `ast-grep run `.. but it appears not to be working:

```sh
ast-grep run -l json --globs '**/tsconfig*.json,!tsconfig.base.json' -p '{ "files": [$$$] }' --selector 'pair'
```

When `ast-grep run `.. is executed I'm also getting back results from `"files"` arrays in my `.eslintrc.json` files. 

### 🙂 Expected behavior

The globs should be respected and in my case occurences in `.eslintrc.json` files should not be returned.

**Comment by HerringtonDarkholme** [comment]
Hi, thanks for report.

This is expected behavior and the behavior aligns with established command line tool like [ripgrep](https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#manual-filtering-globs).

Instead of using `,` in globs, you can pass values to `globs` multiple times

```bash
ast-grep run -l json --globs '**/tsconfig*.json' --globs '!tsconfig.base.json' -p '{ "files": [$$$] }' --selector 'pair'
```

The behavior is the same as ripgrep (in fact, I believe the ast-grep code also reference the honorable ripgrep source)
