### ISSUE TITLE
[feature] add api for applying multiple edits

### ISSUE THREAD

**Issue by Devin-Yeung** [ast-grep/ast-grep#1706]
# ⭐ Suggestion

Hi! Thank you for creating such a great tool! I'm currently using the Rust API to create a code plagiarism checker, where I use ast-grep to preprocess source code (basically normalize all the identifier to a same name). I found that applying the edits is the bottleneck.  (I use [this api](https://docs.rs/ast-grep-core/latest/ast_grep_core/struct.AstGrep.html#method.edit), did I miss anything?) I found it very inefficient because it re-parse the tree after each edit, and if I apply 100 edits, then the overhead on re-parsing is huge. So I think it will be better to **provide an API that apply all edits and re-parse the tree once**.

# 💻 Use Cases

Possible workaround: https://github.com/Devin-Yeung/ast-grep/commit/a0c6ce98ae4bd1fe318d4bace02c143565f067b8

(edit: I think I forget to make sure that edits should in non-increasing order, here's the update: https://github.com/Devin-Yeung/ast-grep/commit/b671833798bdcde44e9b0d71e59d2881d027afb9)

I expect that applying the edits in non-increasing order and then reparse the tree should work. I haven't got the time to write tests, but I have checked the implementation in my applications, it works perfectly.

**Comment by HerringtonDarkholme** [comment]
Hi, thanks for using ast-grep!

> very inefficient because it re-parse the tree after each edit

Yes, the API is used for interactive editing (think you are editing in vscode or zed) and it is not suitable for batch editing.

ast-grep-core does not ship a multiple editing feature because it needs the assumption that edit does not overlap each other.

For example, the confirmation step will exclude overlapping edits. And I believe your use case "renaming identifiers" will not produce overlapping edit. However, that is not the general case.

https://github.com/ast-grep/ast-grep/blob/1c68280bfb9fd2614cab19b4cda47d2bf6570626/crates/cli/src/print/interactive_print.rs#L135-L156

for now, it is possible to apply the edit all at once manually in user land. For example

https://github.com/ast-grep/ast-grep/blob/1c68280bfb9fd2614cab19b4cda47d2bf6570626/crates/cli/src/print/interactive_print.rs#L211-L227

**Comment by Devin-Yeung** [comment]
Oh... I didn't notice the overlapping case 🤔 From intuition, can this issue be resolved by applying non-overlapping edits in "batch" mode? Although we may not be able to complete the edits in a single re-parsing, we can still minimize the number of re-parsings. 

Anyway, I didn't realize that `ast-grep-core` is designed for interactive editing. So, I respect your design of the API. Once again, thank you for your quick and great response. You may choose to mark this issue as closed, or keep it open for those who wish to refer to my "innocent idea." :)

**Comment by HerringtonDarkholme** [comment]
At the moment I don't have a good API design for multiple edits due to overlapping and recursive edit. (e.g. a rule can produce a diff that triggers another rule). 

For now, I deliberately leave the choice to the API consumer, that is, users need to guarantee edits are not overlapping and need to splice the string together themselves.
