### ISSUE TITLE
[feature] Support Dart

### ISSUE THREAD

**Issue by jack-michaud** [ast-grep/ast-grep#172]
My team uses Flutter and I'm curious about adding Dart to this project. 

Dart tree sitter seems pretty young. There's some more discussion over in the nvim-treesitter about adding dart support: https://github.com/nvim-treesitter/nvim-treesitter/issues/213

**Comment by HerringtonDarkholme** [comment]
I have tried dart tree-sitter. Integrating it is easy, but the parser itself has some peculiarity.
Dart tree sitter outputs multiple ast nodes for function declaration instead of one single node, fo rexample

```dart
void abc() {}
```

<img width="450" alt="image" src="https://user-images.githubusercontent.com/2883231/213603389-74d3ea49-9dc6-4576-962f-7596d7e6445c.png">

ast-grep does not support multiple node pattern for now. So writing a query like "void abc() {}" will trigger an error.
Even if multiple node is supported, a kind to match a function is nevertheless desirable.

**Comment by HerringtonDarkholme** [comment]
Another example

<img width="778" alt="image" src="https://user-images.githubusercontent.com/2883231/213604789-da8aa9b6-e692-4e23-a075-58d18f6c2ee1.png">

Note that `method_signature` and `function_body`'s common ancestor is `class_body`. Instead I would usually expect a `method` to group the two ast nodes.

**Comment by HerringtonDarkholme** [comment]
Looks like it faithfully follows Dart language spec.

![image](https://user-images.githubusercontent.com/2883231/213606485-fe43cdc9-f024-444a-95af-22d125f168db.png)

**Comment by HerringtonDarkholme** [comment]
I added initial support for dart now. Note multi node pattern is not supported yet.

**Comment by jack-michaud** [comment]
That's quite an odd quirk of the dart language. Thank you for documenting this quirk and for adding Dart :)

**Comment by HerringtonDarkholme** [comment]
I improved dart tree sitter here for better usability https://github.com/ast-grep/tree-sitter-dart. 
I plan to release it soon.
