### ISSUE TITLE
Underscore is not matched by variable in rust code

### ISSUE THREAD

**Issue by fvictorio** [ast-grep/ast-grep#412]
Doing `sg -p '|$1, $2|'` matches this:

```rust
    let w = v.into_iter().reduce(|x, y| x + y);
```

but not this:

```rust
    let w = v.into_iter().reduce(|x, _| x + x);
```

The `|$A, _|` pattern does match the second snippet, and `|$A, $$$|` matches both.

**Comment by HerringtonDarkholme** [comment]
Hi there, thanks for reporting this!
I'm not available these days and will look at it when I am back.

Thanks for your patience 🙏

**Comment by hpmaxi** [comment]
Hi @HerringtonDarkholme .
Could this be a "good-first-issue"? 

I was checking the second snippet with the wildcard pattern on the tree-sitter playground and `_` doesn't appear as a node.

**Comment by HerringtonDarkholme** [comment]
Hi @hpmaxi, thanks for your interest in ast-grep!

I had a rough look on the issue. This is because `tree-sitter-rust` does not count `_`, the placeholder, as an identifier.
Instead, `_` is just an unnamed node where no kind is presented.

We can verify it by toggle the `show full tree` option in the playground.

<img width="456" alt="image" src="https://github.com/ast-grep/ast-grep/assets/2883231/ab47ced6-728a-4640-be63-5b7dfe1420b3">

`_` is an unnamed node in CST. But `$META` only matches named nodes. However, `$$META` will match all nodes. 
So as an alternative, this pattern can be used.

```
|$$FIRST, $$SECOND|
```

See the [playground](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoicnVzdCIsInF1ZXJ5IjoifCQkRklSU1QsICQkU0VDT05EfCIsImNvbmZpZyI6IiMgQ29uZmlndXJlIFJ1bGUgaW4gWUFNTFxucnVsZTpcbiAgYW55OlxuICAgIC0gcGF0dGVybjogaWYgKGZhbHNlKSB7ICQkJCB9XG4gICAgLSBwYXR0ZXJuOiBpZiAodHJ1ZSkgeyAkJCQgfVxuY29uc3RyYWludHM6XG4gICMgTUVUQV9WQVI6IHBhdHRlcm4iLCJzb3VyY2UiOiJmbiB0ZXN0KCkge1xuICAgIGxldCB3ID0gdi5pbnRvX2l0ZXIoKS5yZWR1Y2UofHgsIHl8IHggKyB5KTtcbiAgICBsZXQgdyA9IHYuaW50b19pdGVyKCkucmVkdWNlKHx4LCBffCB4ICsgeCk7XG59XG4ifQ==). 

Alas, ast-grep users have to learn something about named vs unnamed nodes.

**Comment by fvictorio** [comment]
Oh, I didn't know about unnamed nodes :sweat_smile: In which contexts is this distinction useful from a user-perspective?

Also, feel free to close this issue and open a different one explicitly about documenting this, if that makes your backlog cleaner.

**Comment by HerringtonDarkholme** [comment]
@fvictorio  I have written a simplified explanation of named node and unnamed node in the comment. https://github.com/ast-grep/ast-grep/issues/374#issuecomment-1562481255

It could be a good introduction before I write a good one :)

**Comment by fvictorio** [comment]
I see, thanks for the explanation!
