### ISSUE TITLE
[Question] Pattern syntax - how to escape characters

### ISSUE THREAD

**Issue by josuemontano** [ast-grep/ast-grep#432]
Hi there! I'm not able to find documentation about how to escape characters such as `/<>`. For example, this command

```
sg -p '\/\/ @ts-check'  -r '/** @ts-check */' -l ts src/**/*.tsx --interactive
```

is returning the following error: `Error: Cannot parse query as a valid pattern`. I would greatly appreciate your help. Thank you!

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoidHlwZXNjcmlwdCIsInF1ZXJ5IjoidXNlU3RhdGU8c3RyaW5nIHwgdW5kZWZpbmVkPiIsImNvbmZpZyI6IiMgQ29uZmlndXJlIFJ1bGUgaW4gWUFNTFxucnVsZTpcbiAga2luZDogY2FsbF9leHByZXNzaW9uXG4gIGhhczpcbiAgICBraW5kOiB0ZW1wbGF0ZV9zdHJpbmdcbiAgICBmaWVsZDogYXJndW1lbnRzXG4iLCJzb3VyY2UiOiJpbXBvcnQgeyB1c2VTdGF0ZSB9IGZyb20gJ3JlYWN0J1xuXG5mdW5jdGlvbiBmb290ZXJUZW1wbGF0ZSgpIHtcbiAgICBjb25zdCBbc3RhdGUsIHNldFN0YXRlXSA9IHVzZVN0YXRlPHN0cmluZyB8IHVuZGVmaW5lZD4oKVxuICAgIHJldHVybiA8cD57c3RhdGV9PC9wPlxufVxuIn0=

**Comment by HerringtonDarkholme** [comment]
Hi! Thanks for trying ast-grep out!
For the playground link, the problem is that `func<A | B>` is not a valid TypeScript syntax. You need add `()` to make a valid generic function call.

<img width="1028" alt="image" src="https://github.com/ast-grep/ast-grep/assets/2883231/c5bd795c-0ff0-4ca3-a2fc-fa58c8d4bf78">

[Link](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoidHlwZXNjcmlwdCIsInF1ZXJ5IjoidXNlU3RhdGU8c3RyaW5nIHwgdW5kZWZpbmVkPigkJCQpIiwiY29uZmlnIjoiIyBDb25maWd1cmUgUnVsZSBpbiBZQU1MXG5ydWxlOlxuICBraW5kOiBjYWxsX2V4cHJlc3Npb25cbiAgaGFzOlxuICAgIGtpbmQ6IHRlbXBsYXRlX3N0cmluZ1xuICAgIGZpZWxkOiBhcmd1bWVudHNcbiIsInNvdXJjZSI6ImltcG9ydCB7IHVzZVN0YXRlIH0gZnJvbSAncmVhY3QnXG5cbmZ1bmN0aW9uIGZvb3RlclRlbXBsYXRlKCkge1xuICAgIGNvbnN0IFtzdGF0ZSwgc2V0U3RhdGVdID0gdXNlU3RhdGU8c3RyaW5nIHwgdW5kZWZpbmVkPigpXG4gICAgcmV0dXJuIDxwPntzdGF0ZX08L3A+XG59XG4ifQ==)

For the command, I think it is because `/` does not need escaping in shell. This command works for me.

```shell
sg -p '// @ts-check'  -r '/** @ts-check */' -l ts  --interactive
```

I also confirmed with the `--debug-query` option.

```shell
$ sg -p '// @ts-check'  -l ts  --debug-query
Pattern TreeSitter (comment)
```

**Comment by josuemontano** [comment]
Thanks! You are absolutely right! I was trying this

```
sg -p 'useState<string|undefined>()'  -r 'useState()' -l ts portal/**/*.tsx --interactive
```

instead of
```
sg -p 'useState<string|undefined>($A)'  -r 'useState($A)' -l ts portal/**/*.tsx --interactive
```

Is there any character that needs escaping in shell?

**Comment by HerringtonDarkholme** [comment]
If you are using single quotes `'` as string delimiter in shell, you don't need to escape any character except the `'` itself.
`"` needs to escape `$` sign though.
