### ISSUE TITLE
[feature] support error/warning suppression

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep#446]
### Discussed in https://github.com/ast-grep/ast-grep/discussions/445

<div type='discussions-op-text'>

<sup>Originally posted by **q0w** June  7, 2023</sup>
What do you think about adding support for `# ast-grep: rule-id` mechanism to ignore specific rules on specific lines of code?</div>

- [x] #1005
- [x] #1006
- [x] #1009
- [x] #1007

**Comment by chrisgrieser** [comment]
Came here searching for that. Would indeed like to have such a feature, yes. 

Though, I'd rather call it "ignore via inline comment" or something, since I think `noqa` is mostly only the terminology in python.

Also, to be in line with what other linters commonly do, it should rather be something like `# ast-grep-disable: rule-id`

**Comment by monotkate** [comment]
What are the chances of this feature getting added in the near future? We have a ton of uses ast-grep for custom linting rules, but not having this makes it difficult to roll them out to large files without blocking people on a ton of unrelated changes. Not an ideal scenario in general, but we can get around this with most linters with inline ignores.

**Comment by HerringtonDarkholme** [comment]
Hi @monotkate, thanks for using ast-grep!
I will look at this soon. I will give it back about the timeline for suppression by this weekend. 

Thanks!

**Comment by HerringtonDarkholme** [comment]
Hi @monotkate I have pushed a commit to the main branch and would you like to build the CLI from source? https://github.com/ast-grep/ast-grep?tab=readme-ov-file#installation

I have not had time to test it thoroughly but I would like to collect some early feedback from real-world usage. Thanks!

**Comment by q0w** [comment]
@HerringtonDarkholme how to ignore a specific rule?

**Comment by q0w** [comment]
I guess ast-grep supresses errors but still returns non-exit code
```
Error: 2 error(s) found in code.
Help: Scan succeeded and found error level diagnostics in the codebase.
```

**Comment by monotkate** [comment]
Little bit of work to convince it to use the right version, but it seems to generally work as expected! 
```
# ast-grep-ignore
tags=[f"provider_id:{provider_id}"],
```

Like @q0w mentioned though, it's definitely still returning an error exit (sidenote: I always find it surprising it returns number of files with errors rather than overall number of errors)

<img width="512" alt="image" src="https://github.com/ast-grep/ast-grep/assets/11742296/d5f4155a-c6cb-4a24-badb-4322c8aaf75c">

**Comment by HerringtonDarkholme** [comment]
Thanks for your

**Comment by HerringtonDarkholme** [comment]
Todo List:
- [ ] disable specific rule
- [ ] do not count ignored error in CLI return
- [ ] add test for scanning

**Comment by HerringtonDarkholme** [comment]
Just shipped some new fixes. Feedback welcome!

**Comment by q0w** [comment]
I guess it works

**Comment by q0w** [comment]
> I always find it surprising it returns number of files with errors rather than overall number of errors)

Same

**Comment by HerringtonDarkholme** [comment]
@q0w @chrisgrieser error count is fixed in 0b9c15932072fa9a7662e12bb84e0307a3d54a1f 
thanks for your feedback!

**Comment by HerringtonDarkholme** [comment]
will ship in 0.20.0!

**Comment by HerringtonDarkholme** [comment]
0.20.1 is shipped!
