### ISSUE TITLE
[feature] Github annotations output format

### ISSUE THREAD

**Issue by q0w** [ast-grep/ast-grep#499]
# ⭐ Suggestion
Add an alternative output format to use with GitHub actions annotations.

# 💻 Use Cases

**Comment by HerringtonDarkholme** [comment]
Sorry, I didn't get you. What are annotations?

**Comment by q0w** [comment]
https://user-images.githubusercontent.com/155044/181088096-36eb1d45-5b7d-4f4f-9721-185effbb9115.png

**Comment by q0w** [comment]
This is what [ruff](https://github.com/astral-sh/ruff/) github output format looks like:
```
::error title=Ruff (F401),file=/tmp/t/t.py,line=1,col=8,endLine=1,endColumn=19::t.py:1:8: F401 `collections` imported but unused
::error title=Ruff (F401),file=/tmp/t/t.py,line=2,col=8,endLine=2,endColumn=11::t.py:2:8: F401 `abc` imported but unused
```

**Comment by HerringtonDarkholme** [comment]
Thanks for the suggestion! I have planned integrating GitHub action and release a GH action template.

**Comment by HerringtonDarkholme** [comment]
Some ideas about the option

## Add a new option `--format`

```
-f, --format [lint, github, search]
```

sg scan's default format is linter.  We can change it to search/github for different output. 
Question, why `--json` is a standalone option? 
Answer: because `--json` conflicts with `--interactive`

## Add a new option `--github`
This is more inline with the existing format `--json`. But can --github accept interactive? Will it change its format when piping output to another program. Like `sg run -p | less` will produce different heading.

**Comment by q0w** [comment]
So there is no --format option?

**Comment by HerringtonDarkholme** [comment]
Not released yet.
