### ISSUE TITLE
[feature] supports multiple languages in a rule

### ISSUE THREAD

**Issue by pd4d10** [ast-grep/ast-grep#525]
# ⭐ Suggestion

supports multiple languages in a rule, for example:

```yml
- id: xxx
- languages: [ts, tsx]
```

# 💻 Use Cases

There are many common lint cases in `ts` and `tsx`. It would be great to config them in one rule, to avoid copy and paste.

**Comment by HerringtonDarkholme** [comment]
I'm suspecting if using multiple languages in a rule is the real issue here.

JavaScript and TypeScript looks like the same, but they just **happened** to be similar. Their underlying parsers will produce different ASTs for the same code input.

For example:

```js
(a) => f(a)
```

Will produce different syntax trees. https://github.com/ast-grep/ast-grep/issues/1087

Having two similar but different languages in the same rule will confuse users for parsing discrepancies. 

Instead, the issue here should be rephrased to 

"both JS/TS should be parsed with one language and handled together"

Using language globs is probably the better approach here.
https://ast-grep.github.io/reference/sgconfig.html#languageglobs

**Comment by HerringtonDarkholme** [comment]
Closing as stated above, the more appropriate mental model will be using a superset language to parse subset language via languageGlobs.

**Comment by HerringtonDarkholme** [comment]
More explanation why it is hard to support
https://ast-grep.github.io/advanced/faq.html#how-to-reuse-rule-for-similar-languages-like-ts-js-or-c-c
