### ISSUE TITLE
[bug] The class name won't match the pattern in TypeScript

### ISSUE THREAD

**Issue by PinkChampagne17** [ast-grep/ast-grep#629]
# ⏯ Playground Link

[Playground link with relevant code](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoidHlwZXNjcmlwdCIsInF1ZXJ5IjoiQ2xhc3NOYW1lIiwicmV3cml0ZSI6IiIsImNvbmZpZyI6IiMgWUFNTCBSdWxlIGlzIG1vcmUgcG93ZXJmdWwhXG4jIGh0dHBzOi8vYXN0LWdyZXAuZ2l0aHViLmlvL2d1aWRlL3J1bGUtY29uZmlnLmh0bWwjcnVsZVxucnVsZTpcbiAgYW55OlxuICAgIC0gcGF0dGVybjogY29uc29sZS5sb2coJEEpXG4gICAgLSBwYXR0ZXJuOiBjb25zb2xlLmRlYnVnKCRBKVxuZml4OlxuICBsb2dnZXIubG9nKCRBKSIsInNvdXJjZSI6ImV4cG9ydCBjbGFzcyBDbGFzc05hbWUge31cbmNvbnN0IGluc3QgPSBuZXcgQ2xhc3NOYW1lKCkifQ==)

# 💻 Code

Code:

```typescript
export class ClassName {}
const inst = new ClassName()
```

Pattern:

```yml
ClassName
```

# 🙁 Actual behavior
The first `ClassName` will be matched, but not the second.
If the language is JavaScript, all will be matched.

# 🙂 Expected behavior
The second `ClassName` is also matched.

**Comment by HerringtonDarkholme** [comment]
Hi, thanks for trying out ast-grep.

This is an expected behavior since className is `type_identiier` in TS grammar.

![image](https://github.com/ast-grep/ast-grep/assets/2883231/a2deaabb-1304-4a45-b68c-037f5309356f)

While the single `ClassName` is `identifier`
<img width="403" alt="image" src="https://github.com/ast-grep/ast-grep/assets/2883231/acf79e96-7647-467d-bd4c-bbb9b521d172">


The solution here is to use YAML rule to specify ast more precisely.

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InR5cGVzY3JpcHQiLCJxdWVyeSI6IkNsYXNzTmFtZSIsInJld3JpdGUiOiIiLCJjb25maWciOiJydWxlOlxuICBraW5kOiB0eXBlX2lkZW50aWZpZXJcbiAgcmVnZXg6IENsYXNzTmFtZSIsInNvdXJjZSI6ImNsYXNzIENsYXNzTmFtZSB7fSJ9

<img width="767" alt="image" src="https://github.com/ast-grep/ast-grep/assets/2883231/691da167-c3ac-4827-9c12-9f776a86fbe1">
