### ISSUE TITLE
[bug:rust] can't detect value if it's in a macro

### ISSUE THREAD

**Issue by TornaxO7** [ast-grep/ast-grep#853]
# ⏯ Playground Link

[Playground link with relevant code](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoicnVzdCIsInF1ZXJ5IjoiVGVzdCB7ICRWQUxVRSB9IiwicmV3cml0ZSI6ImxvZ2dlci5sb2coJE1BVENIKSIsImNvbmZpZyI6InJ1bGU6XG4gIGFsbDpcbiAgICAgLSBwYXR0ZXJuOiBwdWIgdXNlICRCOjokQztcbiAgICAgLSBpbnNpZGU6XG4gICAgICAgIGtpbmQ6IHNvdXJjZV9maWxlXG4gICAgICAgIGhhczpcbiAgICAgICAgICBwYXR0ZXJuOiBwdWIgbW9kICRBO1xuICAgICAtIGhhczpcbiAgICAgICAgcGF0dGVybjogJEFcbiAgICAgICAgc3RvcEJ5OiBlbmQiLCJzb3VyY2UiOiJzdHJ1Y3QgVGVzdCB7XG4gICAgYTogaTMyLFxufVxuXG5mbiBtYWluKCkge1xuICAgIGxldCBhID0gdmVjIVtTb21lKFRlc3Qge1xuICAgICAgICBhOiA0MlxuICAgIH0pXTtcbn1mbiJ9)

# 💻 Code

Code:

```rust
struct Test {
    a: i32,
}

fn main() {
    let a = vec![Some(Test {
        a: 42
    })];
}
```

Pattern:

```yml
Test { $VALUE }
```

# 🙁 Actual behavior

`Test { a: 42 }` doesn't get selected.

# 🙂 Expected behavior

`Test { a: 42 }` should get selected.

[Removing the `vec!`](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoicnVzdCIsInF1ZXJ5IjoiVGVzdCB7ICRWQUxVRSB9IiwicmV3cml0ZSI6ImxvZ2dlci5sb2coJE1BVENIKSIsImNvbmZpZyI6InJ1bGU6XG4gIGFsbDpcbiAgICAgLSBwYXR0ZXJuOiBwdWIgdXNlICRCOjokQztcbiAgICAgLSBpbnNpZGU6XG4gICAgICAgIGtpbmQ6IHNvdXJjZV9maWxlXG4gICAgICAgIGhhczpcbiAgICAgICAgICBwYXR0ZXJuOiBwdWIgbW9kICRBO1xuICAgICAtIGhhczpcbiAgICAgICAgcGF0dGVybjogJEFcbiAgICAgICAgc3RvcEJ5OiBlbmQiLCJzb3VyY2UiOiJzdHJ1Y3QgVGVzdCB7XG4gICAgYTogaTMyLFxufVxuXG5mbiBtYWluKCkge1xuICAgIGxldCBhID0gU29tZShUZXN0IHtcbiAgICAgICAgYTogNDJcbiAgICB9KTtcbn0ifQ==) makes it working again:

```rust
struct Test {
    a: i32,
}

fn main() {
    let a = Some(Test {
        a: 42
    });
}
```

**Comment by HerringtonDarkholme** [comment]
This is expected. `Test {..}` inside Rust's macro is parsed as token tree, instead of identifier.

Please see the output in TreeSitter panel. https://ast-grep.github.io/reference/playground

<img width="448" alt="image" src="https://github.com/ast-grep/ast-grep/assets/2883231/d0511bc4-2fbf-4a9c-89d4-572fe82e136a">

**Comment by HerringtonDarkholme** [comment]
Similar issue https://github.com/ast-grep/ast-grep/issues/702

**Comment by TornaxO7** [comment]
oh. Hm... May I ask if you have an idea how to catch the stuff inside the macro?

**Comment by HerringtonDarkholme** [comment]
You can use ast-grep-py or ast-grep/napi to inspect the macro tree programmatically. https://ast-grep.github.io/guide/api-usage.html

**Comment by TornaxO7** [comment]
ok, thank you :)

**Comment by lovasoa** [comment]
Has someone found an easy way to match rust expressions anywhere in the source, including inside macros ?

**Comment by lovasoa** [comment]
@HerringtonDarkholme It looks like it's impossible to use a meta variable because of the way `$expr` is represented inside macros.

I would have expected the following to replace `f(x)` with `g(x)` inside `my_macro!(f(x))`, but it does not : 

```yaml
rule:
  any:
    - pattern:
        selector: token_tree
        context: 'x!(f($arg))'
fix: g($arg)
``` 

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InJ1c3QiLCJxdWVyeSI6IkV4cHI6OlZhbHVlKCRNQVRDSCkiLCJyZXdyaXRlIjoiRXhwcjo6VmFsdWUoJE1BVENILndpdGhfZW1wdHlfc3BhbigpKSIsInN0cmljdG5lc3MiOiJzbWFydCIsInNlbGVjdG9yIjoiIiwiY29uZmlnIjoicnVsZTpcbiAgYW55OlxuICAgIC0gcGF0dGVybjpcbiAgICAgICAgc2VsZWN0b3I6IHRva2VuX3RyZWVcbiAgICAgICAgY29udGV4dDogJ3ghKGYoJGFyZykpJ1xuZml4OiBnKCRhcmcpIiwic291cmNlIjoiYXNzZXJ0X2VxISgkYSlcblxubXlfbWFjcm8hKCkifQ==

Macros are very common in rust (especially in tests), so it would be nice if we could get some pointers to make this work

**Comment by lovasoa** [comment]
Is there a way to pass to ast-grep the syntax tree to match directly, without ast-grep trying to parse it from a string ?

**Comment by lovasoa** [comment]
Is there a way to specify a meta variable inside a has rule, in order to reuse it inside the `fix` ?

In the example above, how would I replace calls to `f` with calls to `g` ?

**Comment by HerringtonDarkholme** [comment]
you can use `pattern: $VAR` to one single node
