### ISSUE TITLE
[bug] Escape problem in String

### ISSUE THREAD

**Issue by websec5331** [ast-grep/ast-grep#883]
# ⏯ Playground Link

[Playground link with relevant code](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoicHl0aG9uIiwicXVlcnkiOiJyJ15bQS1aYS16MC05Xy1dK1xcXFwkJyIsInJld3JpdGUiOiIiLCJjb25maWciOiJyZS5jb21waWxlKHInXltBLVphLXowLTlfLV0rJCcpIiwic291cmNlIjoicideW0EtWmEtejAtOV8tXStcXFxcJCcifQ==)

# 💻 Code

Code:

```
r'^[A-Za-z0-9_-]+\\$'
```

Pattern:

```
r'^[A-Za-z0-9_-]+\\$'
```

# 🙁 Actual behavior

Not matched

# 🙂 Expected behavior

Should be matched

If the string starts with a string start like "r', "f", and "b" in Python, then escape does not work. Both in the playground and in CLI.
Remove the double "\\" is the same.

**Comment by HerringtonDarkholme** [comment]
It is caused by meta variable character replacement. You can use YAML rule instead.

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InB5dGhvbiIsInF1ZXJ5IjoicideW0EtWmEtejAtOV8tXSsnIiwicmV3cml0ZSI6IiIsImNvbmZpZyI6InJ1bGU6XG4gICAga2luZDogc3RyaW5nXG4gICAgcmVnZXg6IFwicicuKydcIiIsInNvdXJjZSI6InInXltBLVphLXowLTlfLV0rXFxcXCQnIn0=

**Comment by websec5331** [comment]
OK, thank you

**Comment by HerringtonDarkholme** [comment]
I think the behavior can be improved by replacing `$` only in meta variable.
